name: pprof
channels:
  - conda-forge
dependencies:
  - python=3.7.1
  - numpy=1.16.1
  - scipy=1.2.1
  - matplotlib=3.0.3
  - pandas=0.24.2
  - ipython=7.4.0
  - jupyter=1.0
  - jupyterlab=0.35.4
  - pytest=4.3.1